# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dagg < Formula
  desc ""
  homepage "https://github.com/rerost/dagg"
  version "0.2.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/rerost/dagg/releases/download/v0.2.1/dagg_0.2.1_Darwin_x86_64.tar.gz"
    sha256 "568f84905ca2df9e00321222ed29a0188e26f2244713cf603d595f8862efc32b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/rerost/dagg/releases/download/v0.2.1/dagg_0.2.1_Linux_x86_64.tar.gz"
    sha256 "b444a292709583747a9a3addb4ed0a57f62bfda86f08526875c71ecd1a75e6a7"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/rerost/dagg/releases/download/v0.2.1/dagg_0.2.1_Linux_arm64.tar.gz"
    sha256 "fba063054bdd94eb77d73f8320d4a7a9cbb94de2c45b7ec7ae733dc4aab671e8"
  end

  def install
    bin.install "dagg"
  end
end
