# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dagg < Formula
  desc ""
  homepage "https://github.com/rerost/dagg"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rerost/dagg/releases/download/v0.2.3/dagg_0.2.3_Darwin_x86_64.tar.gz"
      sha256 "059f7666b2bc021fd6cae1411559361caa1e6e14b3a2496dca81bffd18e58447"

      def install
        bin.install "dagg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rerost/dagg/releases/download/v0.2.3/dagg_0.2.3_Darwin_arm64.tar.gz"
      sha256 "592cce65698f87d6c6dc7251ce47ba05ef7fcf3366e3f9830a54029d395552a2"

      def install
        bin.install "dagg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rerost/dagg/releases/download/v0.2.3/dagg_0.2.3_Linux_x86_64.tar.gz"
      sha256 "877443b41f0e5b04eb64a6d11fef695857861c6afb6486282ca3d96942ead04f"

      def install
        bin.install "dagg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rerost/dagg/releases/download/v0.2.3/dagg_0.2.3_Linux_arm64.tar.gz"
      sha256 "5e3a51d694170bb5659cd6b54c1f32107fbc612ff3802bb8c632b9099bce56e7"

      def install
        bin.install "dagg"
      end
    end
  end
end
