# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Discocat < Formula
  desc ""
  homepage "https://github.com/rerost/issue-creator"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/rerost/discocat/releases/download/v0.1.0/discocat_Darwin_x86_64.tar.gz"
      sha256 "6243b70e47a420deed13ad5c6a41d029d137b04d6994dd653bdfeebb15150232"

      def install
        bin.install "issue-creator"
      end
    end
    on_arm do
      url "https://github.com/rerost/discocat/releases/download/v0.1.0/discocat_Darwin_arm64.tar.gz"
      sha256 "cc35766b6cc8ec65f018989c8f24948ae07c2b13be6c2b5a356d1f77d303d9e5"

      def install
        bin.install "issue-creator"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rerost/discocat/releases/download/v0.1.0/discocat_Linux_x86_64.tar.gz"
        sha256 "e477bafd4093f6a1f5ff4ed048652eee2d9eae463a150c2f3b829b5c712ea5b0"

        def install
          bin.install "issue-creator"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rerost/discocat/releases/download/v0.1.0/discocat_Linux_arm64.tar.gz"
        sha256 "8e34eced8c3f0531e15d506f4b788fc59b34b287c3f592e7849898f9f67bc3b8"

        def install
          bin.install "issue-creator"
        end
      end
    end
  end
end
