# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Discocat < Formula
  desc ""
  homepage "https://github.com/rerost/discocat"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/rerost/discocat/releases/download/v0.1.1/discocat_Darwin_x86_64.tar.gz"
      sha256 "6a36e237b977cc702d986541def77efdaea6c76a90a2d74eddd5f31d740c43fc"

      def install
        bin.install "discocat"
      end
    end
    on_arm do
      url "https://github.com/rerost/discocat/releases/download/v0.1.1/discocat_Darwin_arm64.tar.gz"
      sha256 "226cf5ab4981c2af3ffe9343c124eeb656a895b39b409ad5bf48cfa172602af0"

      def install
        bin.install "discocat"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rerost/discocat/releases/download/v0.1.1/discocat_Linux_x86_64.tar.gz"
        sha256 "fd3f8512facb75211bcc15f71ca74a84ea773fdf3be828c4501c7dea1e41ca22"

        def install
          bin.install "discocat"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rerost/discocat/releases/download/v0.1.1/discocat_Linux_arm64.tar.gz"
        sha256 "65f2b2ece57d872498f934eb20eb27618bdf7ee13c373103ba75b52533acb18c"

        def install
          bin.install "discocat"
        end
      end
    end
  end
end
