# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Giro < Formula
  desc ""
  homepage "https://github.com/rerost/giro"
  version "0.0.20"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rerost/giro/releases/download/v0.0.20/giro_Darwin_x86_64.tar.gz"
      sha256 "60c309e2b0868f8a73e7b2460ea098ab276da59ae1f29f1e86fcf4bee2d2bacc"

      def install
        bin.install "giro"
        bin.install "protoc-gen-reflection-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rerost/giro/releases/download/v0.0.20/giro_Darwin_arm64.tar.gz"
      sha256 "72eb856b154eec83fb02d093c7c0463a0b2047d64da602bb557cd3799b181390"

      def install
        bin.install "giro"
        bin.install "protoc-gen-reflection-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rerost/giro/releases/download/v0.0.20/giro_Linux_x86_64.tar.gz"
        sha256 "8ac70c581795d32c644def974611418db4ee5d47e7091eb5f7a984e4c4726e83"

        def install
          bin.install "giro"
          bin.install "protoc-gen-reflection-server"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rerost/giro/releases/download/v0.0.20/giro_Linux_arm64.tar.gz"
        sha256 "cf32a5e355552a2cd4e5156392e572e2d6f152c53378a33c67a2211ec5e0e5eb"

        def install
          bin.install "giro"
          bin.install "protoc-gen-reflection-server"
        end
      end
    end
  end
end
