# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Html2png < Formula
  desc ""
  homepage "https://github.com/rerost/html2png"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rerost/html2png/releases/download/v0.1.1/html2png_Darwin_x86_64.tar.gz"
      sha256 "370b308c49fe1a99d94e25f0022f32705b82b68fe80f8ecadb6ec9600dbf095d"

      def install
        bin.install "html2png"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rerost/html2png/releases/download/v0.1.1/html2png_Darwin_arm64.tar.gz"
      sha256 "3db709834723ecd78da78339bad5c4f968490abae19025f1f00a6059fb24a268"

      def install
        bin.install "html2png"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rerost/html2png/releases/download/v0.1.1/html2png_Linux_x86_64.tar.gz"
        sha256 "8de606ad4023377c3228e7ad52ff7c4076b6c2cc60b7340654130affe472e91a"

        def install
          bin.install "html2png"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rerost/html2png/releases/download/v0.1.1/html2png_Linux_arm64.tar.gz"
        sha256 "b64fc0cb1d25328bd62d03b1a3c84a0f6b951d6cc6c8553fe4025948a0bb0ec1"

        def install
          bin.install "html2png"
        end
      end
    end
  end
end
