# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Html2png < Formula
  desc ""
  homepage "https://github.com/rerost/html2png"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/rerost/html2png/releases/download/v0.1.0/html2png_Darwin_x86_64.tar.gz"
      sha256 "fc5f7ed88a78956409615671001d2a5689852bf6b75f2ed9e044fb1f2bfca8f7"

      def install
        bin.install "html2png"
      end
    end
    on_arm do
      url "https://github.com/rerost/html2png/releases/download/v0.1.0/html2png_Darwin_arm64.tar.gz"
      sha256 "12673b41f4dbdb1fb41b1b36a9c6c47ae0ae95757cfc0036bb2f70effc7a12a9"

      def install
        bin.install "html2png"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rerost/html2png/releases/download/v0.1.0/html2png_Linux_x86_64.tar.gz"
        sha256 "a1096bede202dbcb95d7d681a1ad2620c48b822eb0e27726057a71f4cbd42ab3"

        def install
          bin.install "html2png"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rerost/html2png/releases/download/v0.1.0/html2png_Linux_arm64.tar.gz"
        sha256 "04b3a72d610e7bacd115d7a945d139fc16f832e6e4b6726f95494d90181c30a2"

        def install
          bin.install "html2png"
        end
      end
    end
  end
end
