# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IssueCreator < Formula
  desc ""
  homepage "https://github.com/rerost/issue-creator"
  version "0.1.15"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rerost/issue-creator/releases/download/v0.1.15/issue-creator_0.1.15_Darwin_x86_64.tar.gz"
      sha256 "6438a1b6198490954bea5b924bf647bd034a6c34e362dcb0fe3b1c5ecde45c3c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rerost/issue-creator/releases/download/v0.1.15/issue-creator_0.1.15_Linux_x86_64.tar.gz"
      sha256 "5f8fa903211c1d4cfe98db826d54087f3da601af35027e7fcbfeba106ac57949"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rerost/issue-creator/releases/download/v0.1.15/issue-creator_0.1.15_Linux_arm64.tar.gz"
      sha256 "3dd96db3cc564472805334f5c79a18255ae747b2242e3f34ece1924cc5bc755c"
    end
  end

  def install
    bin.install "issue-creator"
  end
end
