# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IssueCreator < Formula
  desc ""
  homepage "https://github.com/rerost/issue-creator"
  version "0.4.1"

  on_macos do
    on_intel do
      url "https://github.com/rerost/issue-creator/releases/download/v0.4.1/issue-creator_Darwin_x86_64.tar.gz"
      sha256 "f068b7c0622e28819b756c49e5a95919a6c8c41077feeb0e5e004eb3979fbdcf"

      def install
        bin.install "issue-creator"
      end
    end
    on_arm do
      url "https://github.com/rerost/issue-creator/releases/download/v0.4.1/issue-creator_Darwin_arm64.tar.gz"
      sha256 "e208e9131b2e89e4d3b37f631cdf00290654b4599c2703ff82b3704361e322cd"

      def install
        bin.install "issue-creator"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rerost/issue-creator/releases/download/v0.4.1/issue-creator_Linux_x86_64.tar.gz"
        sha256 "acc2ac3faf4674c17e3646dd473aa472bac348974cd9ec998f10d51869a7a35c"

        def install
          bin.install "issue-creator"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rerost/issue-creator/releases/download/v0.4.1/issue-creator_Linux_arm64.tar.gz"
        sha256 "9c79a18f0c4cecde45633d0c24658e330a46d7cde5f77e5767cb147bb3f3b68d"

        def install
          bin.install "issue-creator"
        end
      end
    end
  end
end
