# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shellm < Formula
  desc ""
  homepage "https://github.com/rerost/shellm"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rerost/shellm/releases/download/v0.1.0/shellm_Darwin_x86_64.tar.gz"
      sha256 "a52311d9aebdecc79399c5b7889fc858e0432ef1b8651887e6d33b77ae191a2e"

      def install
        bin.install "shellm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rerost/shellm/releases/download/v0.1.0/shellm_Darwin_arm64.tar.gz"
      sha256 "2462a613cda407ee818d377e0d0879bfaa46b2646d0679eaefcf1b7582ef6413"

      def install
        bin.install "shellm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rerost/shellm/releases/download/v0.1.0/shellm_Linux_x86_64.tar.gz"
        sha256 "3a397d6258b3bb75fc8de54df65817d606410b89f5c6f37f25eca1cbd1d1f882"

        def install
          bin.install "shellm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rerost/shellm/releases/download/v0.1.0/shellm_Linux_arm64.tar.gz"
        sha256 "bbc08474c8a5ace5bd3df14835700e97a8619e8d0447c3c9a7bcf4622665370f"

        def install
          bin.install "shellm"
        end
      end
    end
  end
end
